"""Patch the lock screen: its colours, font and what it is willing to display.

xsecurelock has no configuration file — it reads environment variables — so this writes the
ones the launcher sources. ``configuration/lock/lock.sh`` holds no appearance of its own, so
a theme change reaches the lock screen without editing anything.

What it deliberately does not show is as much of the point as the colours. A lock screen is
looked at by whoever walks past, so the username, the hostname and the date are all off: they
are free information about you and the machine, offered to someone you are not there to
challenge.
"""

import json
import os
from typing import Any

# Resolves whether this runs as ``helper.patch_lock`` or as a script; see helper/README.md.
try:
    from helper.utils import logger
except ImportError:
    from utils import logger

#: Where the generated environment lands. install.py symlinks configuration/lock/ here.
ENVIRONMENT_PATH = os.path.join("~", ".config", "lock", "environment")

#: Settings that are a decision rather than a colour, with the reason attached.
BEHAVIOUR = {
    # A passer-by learns nothing about who or what this machine is.
    "XSECURELOCK_SHOW_USERNAME": "0",
    "XSECURELOCK_SHOW_HOSTNAME": "0",
    "XSECURELOCK_SHOW_DATETIME": "0",
    # Neither the length of the password nor the fact that one is being typed.
    "XSECURELOCK_PARANOID_PASSWORD": "1",
    # Blank the screen a minute in, so a locked machine is not also a lit one.
    "XSECURELOCK_BLANK_TIMEOUT": "60",
    "XSECURELOCK_BLANK_DPMS_STATE": "off",
    # The first keypress wakes the screen rather than being swallowed by the prompt.
    "XSECURELOCK_DISCARD_FIRST_KEYPRESS": "1",
    "XSECURELOCK_SAVER_DELAY_MS": "0",
}


def lock_environment(configuration: dict[str, Any]) -> dict[str, str]:
    """The variables xsecurelock reads, from the active palette and font."""
    theme = configuration["state"]["theme"]
    palette = configuration["palette"][theme]
    font = configuration["font"]
    return {
        # The screen behind the prompt, and the prompt itself.
        "XSECURELOCK_BACKGROUND_COLOR": palette["background"],
        "XSECURELOCK_AUTH_BACKGROUND_COLOR": palette["background"],
        "XSECURELOCK_AUTH_FOREGROUND_COLOR": palette["foreground"],
        # A wrong password is the one moment the lock screen has something to say.
        "XSECURELOCK_AUTH_WARNING_COLOR": palette["warning"],
        "XSECURELOCK_FONT": f"{font['family']}:size={round(font['size'] * 0.85)}",
        **BEHAVIOUR,
    }


def patch_lock(configuration: dict[str, Any]) -> None:
    path = os.path.expanduser(ENVIRONMENT_PATH)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as handle:
        handle.write("# Generated by helper/patch_lock.py — edits are overwritten.\n")
        for name, value in lock_environment(configuration).items():
            handle.write(f'{name}="{value}"\n')
            handle.write(f"export {name}\n")
    logger.info("Patched lock configuration ...")


if __name__ == "__main__":
    with open(os.path.expanduser("~/.config/config.json")) as input_handle:
        patch_lock(json.load(input_handle))
