"""Patch GTK: what GTK 3 and GTK 4 applications draw with, and how their file chooser opens.

Which mechanism works where was measured rather than assumed, by rendering a window under
each toolkit and sampling the result:

- A user ``@define-color`` does **not** override a stock theme's own definition. Redefining
  ``theme_bg_color`` in ``~/.config/gtk-3.0/gtk.css`` left an Adwaita window exactly as it
  was, still ``#F6F5F4``. GTK 4's built-in theme behaves the same way.
- Ordinary CSS rules do win, because the user stylesheet is loaded after the theme. That is
  how the palette reaches both toolkits.
- libadwaita is the exception: it resolves its named colours at runtime, so
  ``@define-color window_bg_color`` does work there, and is the documented way to recolour
  it. GTK 4 is given both, since an application on that version may be either.

Light and dark is a fourth thing and not CSS at all. GTK 3 reads
``gtk-application-prefer-dark-theme`` from ``settings.ini`` at startup; GTK 4 and libadwaita
watch the ``color-scheme`` GSettings key and follow it live.
"""

import json
import os
import subprocess
from typing import Any

# Resolves whether this runs as ``helper.patch_gtk`` or as a script; see helper/README.md.
try:
    from helper.utils import logger
except ImportError:
    from utils import logger

#: The two toolkit versions installed here, and their configuration directories under
#: ~/.config. GTK 2 is absent from this machine and so from this list.
GTK_DIRECTORIES = ("gtk-3.0", "gtk-4.0")

#: The palette tokens the stylesheet is built from, under the names it refers to them by.
#: Naming the roles rather than the tokens keeps the CSS readable and means a rule says what
#: it is for rather than which colour it happens to use.
ROLES = {
    "surface": "background",
    "on-surface": "foreground",
    "muted": "neutral",
    "accent": "highlight",
    "on-accent": "background",
    "warning": "warning",
    "error": "failure",
    "success": "success",
}

#: libadwaita's own named colours, mapped onto those roles. This is the one place
#: ``@define-color`` reaches anything, and the only supported way to recolour libadwaita
#: without shipping a whole theme.
ADWAITA_COLOURS = {
    "window_bg_color": "surface",
    "window_fg_color": "on-surface",
    "view_bg_color": "surface",
    "view_fg_color": "on-surface",
    "headerbar_bg_color": "surface",
    "headerbar_fg_color": "on-surface",
    "popover_bg_color": "surface",
    "popover_fg_color": "on-surface",
    "dialog_bg_color": "surface",
    "dialog_fg_color": "on-surface",
    "card_bg_color": "surface",
    "card_fg_color": "on-surface",
    "sidebar_bg_color": "surface",
    "sidebar_fg_color": "on-surface",
    "accent_bg_color": "accent",
    "accent_fg_color": "on-accent",
    "accent_color": "accent",
    "destructive_bg_color": "error",
    "destructive_color": "error",
    "success_color": "success",
    "warning_color": "warning",
    "error_color": "error",
}

#: Deliberately few, as (selector, background role, foreground role). Every rule here
#: overrides a stock theme that is otherwise coherent and internally consistent, so each one
#: is a chance to break an application's layout in a way nothing here would notice. These
#: cover the surfaces a window is mostly made of and stop.
RULES = (
    ("window, dialog, .background, popover, popover > contents", "surface", "on-surface"),
    ("headerbar, .titlebar", "surface", "on-surface"),
    ("entry, textview, treeview, list, .view", "surface", "on-surface"),
    ("*:selected, *:selected:focus", "accent", "on-accent"),
)

#: GTK's font size is in points against a size given here in pixels, the same ratio kitty
#: uses for the same reason.
FONT_SIZE_RATIO = 0.714


def gtk_roles(configuration: dict[str, Any]) -> dict[str, str]:
    """The palette colour behind each role name, for the active theme."""
    palette = configuration["palette"][configuration["state"]["theme"]]
    return {role: palette[token] for role, token in ROLES.items()}


def gtk_css(configuration: dict[str, Any], *, adwaita: bool) -> str:
    """The stylesheet one toolkit version reads. ``adwaita`` adds libadwaita's own names."""
    roles = gtk_roles(configuration)
    lines = [
        "/* Generated by helper/patch_gtk.py — edits are overwritten on the next theme"
        " switch. */",
        "",
    ]
    lines += [f"@define-color {role} {colour};" for role, colour in roles.items()]
    if adwaita:
        lines += ["", "/* libadwaita resolves these at runtime, which is why they work. */"]
        lines += [f"@define-color {name} @{role};" for name, role in ADWAITA_COLOURS.items()]
    lines += ["", "/* Stock themes ignore the definitions above; these rules do not. */"]
    for selector, background, foreground in RULES:
        lines.append(
            f"{selector} {{ background-color: @{background}; color: @{foreground}; }}"
        )
    return "\n".join(lines) + "\n"


def gtk_settings(configuration: dict[str, Any]) -> dict[str, str]:
    """The ``[Settings]`` block both versions read at startup."""
    font = configuration["font"]
    return {
        "gtk-theme-name": "Adwaita",
        # GTK 3 has no other way to be told; it does not watch the GSettings key below.
        "gtk-application-prefer-dark-theme": (
            "1" if configuration["state"]["theme"] == "dark" else "0"
        ),
        "gtk-font-name": f"{font['family']} {round(font['size'] * FONT_SIZE_RATIO)}",
    }


def render_settings(settings: dict[str, str]) -> str:
    """settings.ini is a GKeyFile, which wants its section header."""
    body = "".join(f"{key}={value}\n" for key, value in settings.items())
    return f"[Settings]\n{body}"


def gsettings_preferences(configuration: dict[str, Any]) -> tuple[tuple[str, str, str], ...]:
    """(schema, key, value) for everything that is not a file.

    These live in dconf, which is per-user binary state rather than anything this repository
    can track, so they are applied rather than written. Applied on every run, which makes
    them self-healing: a machine where dconf was reset gets them back at the next theme
    switch rather than staying wrong until somebody notices.
    """
    dark = configuration["state"]["theme"] == "dark"
    return (
        # Both toolkits keep their own copy of this, and neither defaults to showing them.
        ("org.gtk.Settings.FileChooser", "show-hidden", "true"),
        ("org.gtk.gtk4.Settings.FileChooser", "show-hidden", "true"),
        # What GTK 4 and libadwaita watch to follow the desktop into dark and back.
        (
            "org.gnome.desktop.interface",
            "color-scheme",
            "prefer-dark" if dark else "prefer-light",
        ),
    )


def apply_gsettings(preferences: tuple[tuple[str, str, str], ...]) -> list[str]:
    """Write each preference that is not already set. Returns the keys actually changed.

    A schema that is not installed is skipped rather than raised: the file chooser keys come
    with the toolkit, so their absence means that toolkit is not installed and there is
    nothing the setting could affect.
    """
    changed = []
    for schema, key, value in preferences:
        try:
            current = subprocess.run(
                ["gsettings", "get", schema, key],
                capture_output=True, text=True, check=False,
            )
        except OSError:
            logger.info("gsettings is unavailable; GTK preferences were not applied.")
            return changed
        if current.returncode != 0:
            continue
        if current.stdout.strip().strip("'") == value:
            continue
        result = subprocess.run(
            ["gsettings", "set", schema, key, value],
            capture_output=True, text=True, check=False,
        )
        if result.returncode == 0:
            changed.append(f"{schema} {key}")
    return changed


def patch_gtk(configuration: dict[str, Any]) -> None:
    for directory in GTK_DIRECTORIES:
        path = os.path.expanduser(os.path.join("~", ".config", directory))
        os.makedirs(path, exist_ok=True)
        with open(os.path.join(path, "gtk.css"), "w") as output_handle:
            output_handle.write(gtk_css(configuration, adwaita=directory == "gtk-4.0"))
        with open(os.path.join(path, "settings.ini"), "w") as output_handle:
            output_handle.write(render_settings(gtk_settings(configuration)))

    for key in apply_gsettings(gsettings_preferences(configuration)):
        logger.info(f"Set {key}.")
    logger.info("Patched GTK configuration ...")


if __name__ == "__main__":
    with open(os.path.expanduser("~/.config/config.json")) as input_handle:
        patch_gtk(json.load(input_handle))
