background #322f2f
selection_background #d5d1d1
foreground #d5d1d1
selection_foreground #322f2f
font_family OverpassM Nerd Font
cursor #fffbfb
color0 #fffbfb
color1 #ffa3a4
color2 #91dca0
color3 #ffb565
color4 #95ceff
color5 #f9a8ee
color6 #71dbe0
color7 #322f2f
color8 #d5d1d1
color9 #cd6869
color10 #569c67
color11 #c07726
color12 #4d91c7
color13 #b66cac
color14 #229ca0
color15 #afabab
