color0=#322f2f
color1=#afabab
color2=#4d91c7
color3=#d5d1d1

bind r source-file ~/.config/tmux/tmux.conf \; display "::: tmux config reloaded :::"

set -g default-terminal "screen-256color"

set -gq mouse on
set -gq status-keys vi

set -gq status-position top
set -gq status-right "#T"
set -qg status-right-length 48
set -qg status-left-length 48

set -gq status-bg "$color0"
set -gq status-fg "$color1"

set -gq base-index 1

set -gq window-status-style fg="$color1",bg="$color0"
set -gq window-status-current-format "#I #W"
set -gq window-status-current-style fg="$color0",bg="$color2"

set -gq message-style fg="$color2",bg="$color0"
set -gq message-command-style fg="$color0",bg="$color2"
set -gq message-line 1

set -gq pane-active-border-style fg="$color2",bg="$color0"
set -gq pane-border-style fg="$color1",bg="$color0"

set -gq mode-style fg="$color0",bg="$color3"

set -gq window-active-style fg="$color1",bg="$color0"
set -gq window-style fg="$color1",bg="$color0"
